name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, @${{ github.actor }}! Thanks for contributing by opening your first issue!"
        pr-message: "Hi, @${{ github.actor }}! Thanks for your contribution of opening your first pull request!"
